set(_CATKIN_CURRENT_PACKAGE "mobile_base")
set(mobile_base_VERSION "1.0.0")
set(mobile_base_MAINTAINER " <TODO@email.com>")
set(mobile_base_PACKAGE_FORMAT "2")
set(mobile_base_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(mobile_base_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(mobile_base_BUILDTOOL_DEPENDS "catkin")
set(mobile_base_BUILDTOOL_EXPORT_DEPENDS )
set(mobile_base_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(mobile_base_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(mobile_base_TEST_DEPENDS )
set(mobile_base_DOC_DEPENDS )
set(mobile_base_URL_WEBSITE "")
set(mobile_base_URL_BUGTRACKER "")
set(mobile_base_URL_REPOSITORY "")
set(mobile_base_DEPRECATED "")